// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP7p2ARkUT-w_pQwaIIK_2rjYJ8lSZ0gc',
    appId: '1:558358802038:web:1d226e2059540e8edc3957',
    messagingSenderId: '558358802038',
    projectId: 'tasktealvue',
    authDomain: 'tasktealvue.firebaseapp.com',
    storageBucket: 'tasktealvue.firebasestorage.app',
    measurementId: 'G-4TKCHXGV8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJN5MeRSqg0PyWavO8HB-0qhYAAGWAtU',
    appId: '1:558358802038:android:82ec9f045b19cfa7dc3957',
    messagingSenderId: '558358802038',
    projectId: 'tasktealvue',
    storageBucket: 'tasktealvue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDmIW6LVPwncThfGg-4do2brpCmyq5Lo',
    appId: '1:558358802038:ios:d35f53a3847ede92dc3957',
    messagingSenderId: '558358802038',
    projectId: 'tasktealvue',
    storageBucket: 'tasktealvue.firebasestorage.app',
    iosBundleId: 'com.example.aetram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDmIW6LVPwncThfGg-4do2brpCmyq5Lo',
    appId: '1:558358802038:ios:d35f53a3847ede92dc3957',
    messagingSenderId: '558358802038',
    projectId: 'tasktealvue',
    storageBucket: 'tasktealvue.firebasestorage.app',
    iosBundleId: 'com.example.aetram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP7p2ARkUT-w_pQwaIIK_2rjYJ8lSZ0gc',
    appId: '1:558358802038:web:10226b9c71ac5d34dc3957',
    messagingSenderId: '558358802038',
    projectId: 'tasktealvue',
    authDomain: 'tasktealvue.firebaseapp.com',
    storageBucket: 'tasktealvue.firebasestorage.app',
    measurementId: 'G-4TDJQ46T6D',
  );
}
